-- 1. Create Data Analyst and Clinician Roles
CREATE ROLE IF NOT EXISTS DATA_ANALYST;
CREATE ROLE IF NOT EXISTS CLINICIAN;

-- 2. Grant basic access to PROD Database
GRANT USAGE ON DATABASE EHDIP_PROD TO ROLE DATA_ANALYST;
GRANT USAGE ON SCHEMA EHDIP_PROD.SILVER TO ROLE DATA_ANALYST;
GRANT USAGE ON SCHEMA EHDIP_PROD.GOLD TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA EHDIP_PROD.GOLD TO ROLE DATA_ANALYST;

GRANT USAGE ON DATABASE EHDIP_PROD TO ROLE CLINICIAN;
GRANT USAGE ON SCHEMA EHDIP_PROD.SILVER TO ROLE CLINICIAN;
GRANT SELECT ON ALL TABLES IN SCHEMA EHDIP_PROD.SILVER TO ROLE CLINICIAN;

-- 3. Dynamic Data Masking Policies
CREATE OR REPLACE MASKING POLICY ssn_mask AS (val string) RETURNS string ->
  CASE
    WHEN CURRENT_ROLE() IN ('CLINICIAN') THEN val
    ELSE '***-**-****'
  END;

CREATE OR REPLACE MASKING POLICY mrn_mask AS (val string) RETURNS string ->
  CASE
    WHEN CURRENT_ROLE() IN ('CLINICIAN') THEN val
    ELSE '***-REDACTED-***'
  END;

CREATE OR REPLACE MASKING POLICY dob_mask AS (val date) RETURNS date ->
  CASE
    WHEN CURRENT_ROLE() IN ('CLINICIAN') THEN val
    -- Data analysts only need the year for aggregate metrics
    WHEN CURRENT_ROLE() IN ('DATA_ANALYST') THEN DATE_TRUNC('year', val)
    ELSE NULL
  END;

-- 4. Apply Masking Policies to Silver Tables
-- Assuming the Silver person table has these raw fields before full de-id in this scenario,
-- or this applies to views on top of Silver.
ALTER TABLE EHDIP_PROD.SILVER.person MODIFY COLUMN ssn_masked SET MASKING POLICY ssn_mask;
ALTER TABLE EHDIP_PROD.SILVER.person MODIFY COLUMN mrn_masked SET MASKING POLICY mrn_mask;
ALTER TABLE EHDIP_PROD.SILVER.person MODIFY COLUMN birth_datetime SET MASKING POLICY dob_mask;
