-- Day 9: Snowflake Security, Dynamic Masking & RBAC

USE ROLE ACCOUNTADMIN;
USE DATABASE EHDIP_PROD;
USE SCHEMA SECURITY;

-- 1. Create RBAC Roles
CREATE OR REPLACE ROLE EHDIP_DATA_SCIENTIST;
CREATE OR REPLACE ROLE EHDIP_COMPLIANCE_OFFICER;

-- 2. Create Dynamic Masking Policies for PHI
-- Masking for SSN
CREATE OR REPLACE MASKING POLICY mask_ssn AS (val string) RETURNS string ->
  CASE
    WHEN CURRENT_ROLE() IN ('EHDIP_COMPLIANCE_OFFICER', 'ACCOUNTADMIN') THEN val
    ELSE '***-**-****'
  END;

-- Masking for MRN
CREATE OR REPLACE MASKING POLICY mask_mrn AS (val string) RETURNS string ->
  CASE
    WHEN CURRENT_ROLE() IN ('EHDIP_COMPLIANCE_OFFICER', 'ACCOUNTADMIN') THEN val
    ELSE '***-MASKED-MRN-***'
  END;

-- Masking for DOB (Year only for Safe Harbor)
CREATE OR REPLACE MASKING POLICY mask_dob AS (val date) RETURNS date ->
  CASE
    WHEN CURRENT_ROLE() IN ('EHDIP_COMPLIANCE_OFFICER', 'ACCOUNTADMIN') THEN val
    ELSE DATE_TRUNC('YEAR', val)
  END;

-- 3. Apply Masking Policies to Silver Tables (Assuming they are mapped as standard tables/views for this example, or applied in dbt)
-- Example application on a hypothetical raw patient view
-- ALTER VIEW EHDIP_PROD.SILVER.vw_patient_phi MODIFY COLUMN ssn SET MASKING POLICY mask_ssn;
-- ALTER VIEW EHDIP_PROD.SILVER.vw_patient_phi MODIFY COLUMN mrn SET MASKING POLICY mask_mrn;
-- ALTER VIEW EHDIP_PROD.SILVER.vw_patient_phi MODIFY COLUMN dob SET MASKING POLICY mask_dob;

-- 4. Grant Access
GRANT USAGE ON DATABASE EHDIP_PROD TO ROLE EHDIP_DATA_SCIENTIST;
GRANT USAGE ON SCHEMA EHDIP_PROD.GOLD TO ROLE EHDIP_DATA_SCIENTIST;
GRANT SELECT ON ALL TABLES IN SCHEMA EHDIP_PROD.GOLD TO ROLE EHDIP_DATA_SCIENTIST;

GRANT USAGE ON DATABASE EHDIP_PROD TO ROLE EHDIP_COMPLIANCE_OFFICER;
GRANT USAGE ON SCHEMA EHDIP_PROD.SILVER TO ROLE EHDIP_COMPLIANCE_OFFICER;
GRANT SELECT ON ALL TABLES IN SCHEMA EHDIP_PROD.SILVER TO ROLE EHDIP_COMPLIANCE_OFFICER;
