# src/ingestion/cdc_consumer.py

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, current_timestamp, expr, lit, from_json
from pyspark.sql.types import StructType, StructField, StringType, MapType

def get_spark_session():
    return SparkSession.builder \
        .appName("Debezium_CDC_Batch_Consumer") \
        .getOrCreate()

def process_cdc_batch(spark, s3_cdc_path, iceberg_table):
    """
    Processes Debezium CDC change logs and writes to Bronze Iceberg.
    """
    # Define a schema for Debezium events (simplified)
    schema = StructType([
        StructField("payload", StructType([
            StructField("op", StringType(), True), # c, u, d
            StructField("after", MapType(StringType(), StringType()), True),
            StructField("before", MapType(StringType(), StringType()), True)
        ]), True)
    ])

    # Read JSON logs generated by Kafka Connect / Debezium sinking to S3
    df_raw = spark.read.json(s3_cdc_path)

    # Filter for valid CDC operations
    df_filtered = df_raw.filter(col("payload.op").isin('c', 'u', 'd'))

    # Prepare for Bronze ingestion
    # Convert the whole row to JSON string as raw payload
    df_transformed = df_filtered \
        .withColumn("payload_id", expr("uuid()")) \
        .withColumn("source_system_id", lit("debezium_cdc_postgres")) \
        .withColumn("raw_payload_json", col("payload").cast("string")) \
        .withColumn("ingestion_timestamp", current_timestamp()) \
        .select("payload_id", "source_system_id", "raw_payload_json", "ingestion_timestamp")

    # Append to Bronze Iceberg
    df_transformed.write \
        .format("iceberg") \
        .mode("append") \
        .saveAsTable(iceberg_table)

if __name__ == "__main__":
    spark = get_spark_session()

    # Configuration
    S3_CDC_PATH = "s3://ehdip-datalake-landing-123456789012/cdc/postgres/public.patients/*"
    ICEBERG_TABLE = "glue_catalog.bronze.raw_cdc_payload"

    process_cdc_batch(spark, S3_CDC_PATH, ICEBERG_TABLE)
